# Code to clean up Rwanda CHAIN IP data -----------------------------------
# Laura Hughes, April 2016, lhughes@usaid.gov
# Note: this code isn't impeccably documented, so please send questions 
# if needed and I can clean it up. It's documented to make sense to me (hopefully) but probably makes no sense to others.


# Installing packages ------------------------------------------------
# In Mac OS X, need to install GDAL first.
# In terminal, install macports: https://www.macports.org/install.php
# Then 'sudo port install gdal'
# Go back to R and install rgdal
# install.packages("rgdal",  type="source")

# AND then rgeos.
# http://tlocoh.r-forge.r-project.org/mac_rgeos_rgdal.html
# Reinstall R, since El Capitan has problems w/ saving to usr/lib 
# Install geos: http://www.kyngchaos.com/ 
# Then install :

library(llamar)
library(splitstackshape) 
library(rgdal)
library(maptools)
library(rgeos)
library(raster)
library(rasterVis)
loadPkgs()


# Import and clean “raw” data -----------------------------------------------------

# geo data ----------------------------------------------------------------

# Raw shapefile in R
rwShp <- readShapePoly('~/Documents/USAID/Rwanda/data in/Rwanda_Admin3/Rwanda_Admin_Three.shp')

rwAdm3 = rwShp@data %>% 
  mutate(Province = ifelse(Province == 'Iburengerazuba',
                           'Western Province', as.character(Province))) %>%  # Iburengerazuba == West
  group_by(District) %>% 
  mutate(isDistrict = dense_rank(Sector), # Create a flag if the data are district-level
         isDistrict = ifelse(isDistrict == 1, 1, 0))



# Pull out all the Adm2 names for each Adm1
findAdm2 = function(adm1Name){
  districts = rwAdm3 %>% 
    filter(isDistrict == 1,
           Province %like% adm1Name) %>% 
    select(District)
  
  districts = unique(as.character(districts$District)) # Eliminate duplicates; converts from a factor to a character
  
  districts = paste0(districts, collapse = ', ') # Convert to a string
}

northDistricts = findAdm2('North')
southDistricts = findAdm2('South')
eastDistricts = findAdm2('East')
westDistricts = findAdm2('West')
kigaliDistricts = findAdm2('Kigali')
allDistricts = paste(northDistricts, southDistricts, kigaliDistricts,
                     eastDistricts, westDistricts, sep = ', ')


# Project locations -------------------------------------------------------
df = read_excel('~/Documents/USAID/Rwanda/CHAIN/datain/Locations of CHAIN IMs in Rwanda (2016-03-22).xlsm')

# Cleanup #1: rename columns
# Fix any values that are "all" region/country
df2 = df %>% 
  select(-`To include by Geo Center?`) %>% # Drop unneeded columns
  rename(project = Project,
         mechanism = `Implementing Mechanism`,
         IP = `Implementing Partner`,
         manager = `AOR/COR or Activity Manager`,
         nationwide = `Nationwide?\r\n(If yes, skip the remaining columns)`) %>% # rename so easier to deal with
  mutate(nationwide = ifelse(nationwide %in% c('Yes', 'yes', 'Y', 'y'), # If all of the province or country are selected, convert to a list of the Adm2 names.
                             allDistricts, NA),
         `Kigali Province` = ifelse(`Kigali Province` %like% 'All', 
                                    kigaliDistricts, `Kigali Province`),
         `Northern Province` = ifelse(`Northern Province` %like% 'All', 
                                      northDistricts, `Northern Province`),
         `Southern Province ` = ifelse(`Southern Province ` %like% 'All', 
                                       southDistricts, `Southern Province `),
         `Eastern Province` = ifelse(`Eastern Province` %like% 'All', 
                                     eastDistricts, `Eastern Province`),
         `Western Province` = ifelse(`Western Province` %like% 'All', 
                                     westDistricts, `Western Province`))

# Split Nationwide
df2 = cSplit(df2, 'nationwide', ',')


# Split Kigali
df2 = cSplit(df2, 'Kigali Province', ',')

# Split Northern
df2 = cSplit(df2, 'Northern Province', ',')

# Split Western
df2 = cSplit(df2, 'Western Province', ',')

# Split Southern
df2 = cSplit(df2, 'Southern Province ', ',')

# Split Eastern
df2 = cSplit(df2, 'Eastern Province', ',')

# Convert to a tidy data frame
df2 = df2 %>% 
  gather(regCol, District, -project, -mechanism, -IP, -manager) %>% # convert from wide to long df
  select(-regCol) %>% # Remove column generated by gathering
  filter(!is.na(District), District != 'N/A') # remove NAs


# Add in the results data -----------------------------------------------------------------

results = read_excel('~/Documents/USAID/Rwanda/CHAIN/datain/RF Map to Partners.xlsx')
codebook = read_excel('~/Documents/USAID/Rwanda/CHAIN/datain/Partner Lookup Table.xlsx')

# Split the column based on the comma
results = cSplit(results, 'Partners', ',') %>% 
  gather(partnerNum, partner, -Level, -Result, -INWA) %>% # Convert from wide to long dataset
  select(-partnerNum) %>%  # Remove artifact of split/gather
  filter(!is.na(partner)) %>% # Remove blank lines
  mutate(INWA = ifelse(INWA %like% 'No INWA', 0, 1)) # Convert to binary


# Translate the results into the full file
results = left_join(results, codebook, by = c("partner" = "Code"))

# Merge df w/ Adm names ---------------------------------------------------
df_full = full_join(df2, rwAdm3, by = c("District" = "District")) 

df_full = full_join(df_full, results, by = c("IP" = "Implementing Partner",
                                             "mechanism" = "Implementing Mechanism")) %>% 
  ungroup() %>% 
  group_by(Province, District, Sector, mechanism) %>% 
  mutate(isSector = dense_rank(Result),
         isSector = ifelse(is.na(isSector), 1,
                           ifelse(isSector == 1, 1, 0)))


# Save the results
write.csv(df_full, '~/Documents/USAID/Rwanda/CHAIN/dataout/RW_projects.csv')

ggplot(df2, aes(x = District)) +
  geom_bar(stat = 'count') +
  facet_wrap(~IP)


# Read in .shp files ------------------------------------------------------

# Admin 2
setwd('~/Documents/USAID/Rwanda/data in/Rwanda_Admin2/')
rw = readOGR(dsn=".", layer="District_Boundary_2006")
rw@data$id = rownames(rw@data)
rw.points = fortify(rw, region="id")
rw.df = plyr::join(rw.points, rw@data, by="id")

# Admin 1
setwd('~/Documents/USAID/Rwanda/data in/Rwanda_Admin1/')
rw_adm1 = readOGR(dsn=".", layer="Province_Boundary_2006")
rw_adm1@data$id = rownames(rw_adm1@data)
adm1.points = fortify(rw_adm1, region="id")
adm1.df = plyr::join(adm1.points, rw_lakes@data, by="id")


# Admin 0
setwd('~/Documents/USAID/Rwanda/data in/Rwanda basemaps/')
rw_adm0 = readOGR(dsn=".", layer="RWA_Adm0")
rw_adm0@data$id = rownames(rw_adm0@data)
adm0.points = fortify(rw_adm0, region="id")
adm0.df = plyr::join(adm0.points, rw_lakes@data, by="id")

ggplot(adm0.df) + 
  aes(x = long, y = lat) +
  geom_path(aes(group = id),
            color= grey70K, size = 0.25) +
  scale_x_continuous(limits = range(adm0.df$long) + c(0.001, -0.001)) +
  scale_y_continuous(limits = range(adm0.df$lat) + c(0.001, -0.001)) +
  theme_blank()

# Lakes
setwd('~/Documents/USAID/Rwanda/data in/Rwanda basemaps/')
rw_lakes = readOGR(dsn=".", layer="RWA_Lakes")
rw_lakes@data$id = rownames(rw_lakes@data)
lakes.points = fortify(rw_lakes, region="id")
lakes.df = plyr::join(lakes.points, rw_lakes@data, by="id")

# Terrain
rw_terrain = readGDAL('~/Documents/USAID/Rwanda/data in/Rwanda basemaps/RWA_Terrain.tif')

rw_terrain = raster('~/Documents/USAID/Rwanda/data in/Rwanda basemaps/RWA_Terrain.tif')

map.df <- data.frame(rasterToPoints(rw_terrain))



# Pull out the centroids of the coords and the names of the districts
rw.centroids = data.frame(coordinates(rw)) %>% 
  rename(long = X1, lat = X2)

rw.centroids = cbind(rw.centroids,
                     district = rw@data$District)

adm1.centroids = data.frame(coordinates(rw_adm1)) %>% 
  rename(long = X1, lat = X2)

adm1.centroids = cbind(adm1.centroids,
                     province = rw_adm1@data$Prov_Name)


# Maps! Basic names -------------------------------------------------------
colourRegions = '#fc8d59'
colourLakes = '#a6cee3'


x = ggplot(adm1.df) + 
  aes(x = long, y = lat) +
  geom_polygon(aes(group = id),
               fill = grey30K) +
  geom_path(aes(group = id),
            colour = 'white',
            data = rw.df,
            size = 0.1) +
  geom_path(aes(group = id, colour = id),
            size = 0.2) +
  geom_polygon(aes(group = id), #lakes
               fill = colourLakes,
               data = lakes.df) +
  coord_equal() +
  theme_blank() +
  scale_colour_brewer(palette = 'Set1') +
  # scale_colour_manual(values =c('Northern Province' = '#377eb8',
                                # 'Kigali City' ='#e41a1c',
                                # 'Western Province' = '#ff7f00',
                                # 'Southern Province' = '#984ea3',
                                # 'Eastern Province' = '#4daf4a')) +
  geom_text(aes(x = long, y = lat, label = district),
            data = rw.centroids,
            colour = grey90K,
            size = 1.2) +
  geom_text(aes(x = long, y = lat, label = province),
            data = adm1.centroids,
            colour = grey90K,
            size = 2)

ggsave('~/Documents/USAID/Rwanda/CHAIN/plots/rwanda_labeled.pdf', 
       width = 5, height = 3.5,
       bg = 'transparent',
       paper = 'special',
       units = 'in',
       useDingbats=FALSE,
       compress = FALSE,
       dpi = 300)



# Maps! (CHAIN)-------------------------------------------------------------------


df_adm2 = df_full %>% 
  filter(isDistrict == 1, 
         isSector == 1) %>% 
  select(-Sector, -Sect_ID, -isSector)


df_CHAIN_dist = df_adm2 %>% 
  filter(project %like% 'CHAIN') %>% 
  group_by(mechanism, Province) %>% 
  summarise(numProj_adm1 = n()) %>%
  ungroup() %>% 
  group_by(mechanism) %>% 
  mutate(numProj = sum(numProj_adm1)) %>% 
  ungroup() %>% 
  arrange(desc(numProj))

orderCHAIN_dist = df_CHAIN_dist %>% 
  select(mechanism, numProj) %>% 
  distinct()

# Refactorize
df_adm2$mechanism = factor(df_adm2$mechanism,
                           levels = orderCHAIN_dist$mechanism)

df_adm2$Province = factor(df_adm2$Province, levels = c( 
  'Northern Province',
  'Kigali City',
  'Western Province',
  'Southern Province',
  'Eastern Province'))

rw.df2 = full_join(rw.df, df_adm2, by = c("Prov_ID", "Dist_ID", "District"))

y = rw.df2 %>% 
  filter(project %like% 'CHAIN')



x = ggplot(rw.df) + 
  aes(x = long, y = lat) +
  geom_polygon(aes(group = id),
               fill = grey30K) +
  geom_polygon(aes(group = id, fill = Province), 
               # fill = colourRegions,
               data = y) +
  geom_path(aes(group = id),
            color="white", size = 0.1) +
  geom_polygon(aes(group = id), #lakes
               fill = colourLakes,
               data = lakes.df) +
  facet_wrap(~ mechanism) +
  coord_equal() +
  theme_blank() +
  scale_fill_manual(values =c('Northern Province' = '#377eb8',
                              'Kigali City' ='#e41a1c',
                              'Western Province' = '#ff7f00',
                              'Southern Province' = '#984ea3',
                              'Eastern Province' = '#4daf4a'))
# geom_text(aes(x = long, y = lat, label = district), 
# data = rw.centroids,
# colour = grey90K,
# size = 0.7)

ggsave('~/Documents/USAID/Rwanda/CHAIN/plots/chain.pdf', 
       width = 10, height = 7,
       bg = 'transparent',
       paper = 'special',
       units = 'in',
       useDingbats=FALSE,
       compress = FALSE,
       dpi = 300)


# CHAIN plots — # / Province ----------------------------------------------
mechanisms = unique(df_CHAIN_dist$mechanism)

# for (i in seq_along(mechanisms)){
# dfBar = df_CHAIN_dist %>% 
#   filter(mechanism == mechanisms[i])
dfBar = df_CHAIN_dist

# orderByMech = dfBar %>% 
#   arrange(numProj_adm1)

orderByMech =  c('Kigali City', 
                 'Northern Province',
                 'Western Province',
                 'Southern Province',
                 'Eastern Province')

dfBar$Province = factor(dfBar$Province, 
                        levels = orderByMech)


ggplot(dfBar, aes(x = Province, y = numProj_adm1, 
                  fill = Province, label = numProj_adm1)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(colour = 'white', size = 4,
            nudge_y = -0.3, 
            family = 'Segoe UI') +
  scale_fill_manual(values =c('Northern Province' = '#377eb8',
                              'Kigali City' ='#e41a1c',
                              'Western Province' = '#ff7f00',
                              'Southern Province' = '#984ea3',
                              'Eastern Province' = '#4daf4a')) +
  theme_xylab() +
  facet_wrap(~mechanism) +
  theme(axis.title = element_blank(), 
        axis.text.x = element_blank())

ggsave(paste0('~/Documents/USAID/Rwanda/CHAIN/plots/chain_bar.pdf'), 
       width = 9, height = 5,
       bg = 'transparent',
       paper = 'special',
       units = 'in',
       useDingbats=FALSE,
       compress = FALSE,
       dpi = 300)
# }

# CHAIN: # overall
ggplot(df_CHAIN_dist, aes(x = mechanism, y = 1, 
                          label = paste0(numProj, ' districts'), 
                          fill = numProj)) +
  geom_tile() +
  geom_text(colour = grey90K, family = 'Segoe UI', size = 3) +
  scale_fill_gradient(low = grey15K, high  = grey60K) +
  theme_labelsOnly()

ggsave(paste0('~/Documents/USAID/Rwanda/CHAIN/plots/chain_totalDist.pdf'), 
       width = 6, height = 3,
       bg = 'transparent',
       paper = 'special',
       units = 'in',
       useDingbats=FALSE,
       compress = FALSE,
       dpi = 300)

# CHAIN by results --------------------------------------------------------
df_CHAIN = df_full %>% 
  filter(isDistrict == 1,
         project %like% 'CHAIN') %>% 
  select(-Sector, -Sect_ID, -isSector) %>% 
  group_by(Province, Prov_ID, 
           District, Dist_ID, Result) %>% 
  summarise(numProj = n()) 

orderCHAIN = df_CHAIN %>% 
  ungroup() %>% 
  group_by(Result) %>%
  mutate(numProj = sum(numProj)) %>% 
  ungroup() %>% 
  arrange(desc(numProj)) %>% 
  select(Result, numProj) %>% 
  distinct()


# Refactorize
df_CHAIN$Result = factor(df_CHAIN$Result,
                         levels = orderCHAIN$Result)

rwCHAIN = right_join(rw.df, df_CHAIN, by = c("Prov_ID", "Dist_ID", "District"))

x = ggplot(rw.df) + 
  aes(x = long, y = lat) +
  geom_polygon(aes(group = id),
               fill = grey30K) +
  geom_polygon(aes(group = id,
                   fill = numProj),
               data = rwCHAIN) +
  geom_path(aes(group = id),
            color= grey75K, size = 0.1) +
  geom_polygon(aes(group = id), #lakes
               fill = colourLakes,
               data = lakes.df) +
  facet_wrap(~ Result) +
  coord_equal() +
  theme_blank() +
  scale_fill_gradientn(colours = brewer.pal(9, 'YlGnBu')) +
  geom_text(aes(x = long, y = lat, label = district), 
            data = rw.centroids,
            colour = grey90K,
            size = 0.7) +
  theme(strip.text = element_text(size = 5))

ggsave('~/Documents/USAID/Rwanda/CHAIN/plots/chain_byResult.pdf', 
       width = 10, height = 7,
       bg = 'transparent',
       paper = 'special',
       units = 'in',
       useDingbats=FALSE,
       compress = FALSE,
       dpi = 300)


# Comparison of where work on CHAIN ---------------------------------------

colour1 = '#0868ac'
colour2 = '#ffff33'
colourLakes = '#deebf7'

rw_CHAIN_proj = rw.df2 %>% 
  filter(project %like% 'CHAIN')

mechanisms = unique(rw_CHAIN_proj$mechanism)

counter = 1
plot_list = list()

for (i in 1:7){
  for (j in 1:7){
    print(counter)
    
    y = rw_CHAIN_proj %>% 
      filter(mechanism == mechanisms[i])
    
    z = rw_CHAIN_proj %>% 
      filter(mechanism == mechanisms[j])
    
    p = ggplot(rw_CHAIN_proj) + 
      aes(x = long, y = lat, group = id)+
      geom_polygon(fill = grey15K) +
      geom_polygon(fill = colour1, alpha = 0.6, data = y) +
      geom_polygon(fill = colour2, alpha = 0.6, data = z) +
      geom_polygon(aes(group = id), #lakes
                   fill = colourLakes,
                   data = lakes.df) +
      geom_path(color="white", size = 0.1) +
      coord_equal() +
      theme_blank() +
      theme(title = element_text(size = 3)) +
      ggtitle(paste(mechanisms[i], mechanisms[j], sep = ' & '))
    
    plot_list[[counter]] = p
    
    
    ggsave(paste0('~/Documents/USAID/Rwanda/CHAIN/plots/chain_overlap',
                  counter, '.pdf', collapse = ''),
           width = 3.5,
           height = 2,
           bg = 'transparent',
           paper = 'special',
           units = 'in',
           useDingbats=FALSE,
           compress = FALSE,
           dpi = 300)
    
    counter = counter + 1
  }}





# FtF ---------------------------------------------------------------------

y = rw.df2 %>% 
  filter(project %like% 'FTF')

x = ggplot(rw.df) + 
  aes(x = long, y = lat, group = id)+
  geom_polygon(fill = grey30K) +
  geom_polygon(fill = colourRegions, data = y) +
  geom_path(color="white", size = 0.1) +
  geom_polygon(aes(group = id), #lakes
               fill = colourLakes,
               data = lakes.df) +
  facet_wrap(~ mechanism) +
  coord_equal() +
  theme_blank()


ggsave('~/Documents/USAID/Rwanda/CHAIN/plots/ftf.pdf', 
       width = 10, height = 7,
       bg = 'transparent',
       paper = 'special',
       units = 'in',
       useDingbats=FALSE,
       compress = FALSE,
       dpi = 300)



# Purple ------------------------------------------------------------------

y = rw.df2 %>% 
  filter(project %like% 'Purple')

x = ggplot(rw.df) + 
  aes(x = long, y = lat, group = id)+
  geom_polygon(fill = grey30K) +
  geom_polygon(fill = colourRegions, data = y) +
  geom_path(color="white", size = 0.1) +
  geom_polygon(aes(group = id), #lakes
               fill = colourLakes,
               data = lakes.df) +
  facet_wrap(~ mechanism) +
  coord_equal() +
  theme_blank()

ggsave('~/Documents/USAID/Rwanda/CHAIN/plots/purple.pdf',
       width = 10, height = 7,
       bg = 'transparent',
       paper = 'special',
       units = 'in',
       useDingbats=FALSE,
       compress = FALSE,
       dpi = 300)


# non-map viz -------------------------------------------------------------

df_adm2$District = factor(df_adm2$District, levels = c('Gasabo', 'Kicukiro','Nyarugenge', 'Burera','Gakenke','Gicumbi','Musanze','Rulindo','Bugesera', 'Gatsibo', 'Kayonza',  'Kirehe',   'Ngoma','Nyagatare','Rwamagana','Gisagara',    'Huye', 'Kamonyi', 'Muhanga','Nyamagabe',  'Nyanza','Nyaruguru', 'Ruhango',  'Karongi','Ngororero',  'Nyabihu','Nyamasheke',   'Rubavu',   'Rusizi',  'Rutsiro'))

x = df_adm2 %>% filter(project %like% 'CHAIN')

orderMech = x %>% 
  group_by(mechanism) %>% 
  summarise(num = n()) %>% 
  arrange(desc(num))

x$mechanism = factor(x$mechanism, levels = 
                       orderMech$mechanism)

ggplot(x, aes(x = District, y = mechanism)) +
  geom_point(size = 5, colour = 'dodgerblue')


# with basemap ------------------------------------------------------------

basemap = get_map(location = 'Kigali Rwanda', 
                  zoom = 9, source = 'google', maptype = 'terrain',
                  color = 'bw')

x = ggmap(basemap, darken = c(0.4,'black')) +
  # aes(x = long, y = lat)+
  # geom_polygon(aes(x = long, y = lat, group = id),
  # fill = grey30K, alpha = 0.3) +
  geom_polygon(aes(x = long, y = lat,
                   group = id,fill = id, alpha = 0.3), data = y) +
  geom_path(aes(x = long, y = lat,group = id),
            color="white", size = 0.1, data= y) +
  # coord_equal() +
  theme_blank() +
  geom_text(aes(x = long, y = lat, label = district), 
            data = rw.centroids,
            colour = grey90K,
            size = 0.7)

ggsave('~/Documents/USAID/Rwanda/CHAIN/plots/test.pdf',
       bg = 'transparent',
       paper = 'special',
       units = 'in',
       useDingbats=FALSE,
       compress = FALSE,
       dpi = 300)
