# Code to clean up Rwanda CHAIN IP data -----------------------------------
# Laura Hughes, April 2016, lhughes@usaid.gov

library(llamar)
library(splitstackshape) 
loadPkgs()


# Import and clean “raw” data -----------------------------------------------------


# Project locations -------------------------------------------------------
df = read_excel('~/Documents/USAID/Rwanda/CHAIN/datain/Locations of CHAIN IMs in Rwanda (2016-03-22).xlsm')

# Split Kigali
df2 = cSplit(df, 'Kigali Province', ',')

# Split Northern
df2 = cSplit(df2, 'Northern Province', ',')

# Split Western
df2 = cSplit(df2, 'Western Province', ',')

# Split Southern
df2 = cSplit(df2, 'Southern Province ', ',')

# Split Eastern
df2 = cSplit(df2, 'Eastern Province', ',')

# Cleanup time.
df2 = df2 %>% 
  select(-`To include by Geo Center?`, -V12) %>% # Drop unneeded columns
  rename(project = Project,
         mechanism = `Implementing Mechanism`,
         IP = `Implementing Partner`,
         manager = `AOR/COR or Activity Manager`,
         nationwide = `Nationwide?\r\n(If yes, skip the remaining columns)`) %>% # rename so easier to deal with
  gather(regCol, district, -project, -mechanism, -IP, -manager, -nationwide) %>% # convert from wide to long df
  select(-regCol) %>% # Remove column generated by gathering
  filter(!is.na(district), district != 'N/A' | nationwide == 'Yes' | nationwide == 'Y' | nationwide == 'yes' | nationwide == 'y') # remove NAs (saving the nation-wide pgrms)
# Remove duplicate rows

# Results -----------------------------------------------------------------

results = read_excel('~/Documents/USAID/Rwanda/CHAIN/datain/RF Map to Partners.xlsx')


# Split the column based on the comma
results = cSplit(results, 'Partners', ',') %>% 
  gather(partnerNum, partner, -Level, -Result, -INWA) %>% # Convert from wide to long dataset
  select(-partnerNum) %>%  # Remove artifact of split/gather
  filter(!is.na(partner)) %>% # Remove blank lines
  mutate(INWA = ifelse(INWA %like% 'No INWA', 0, 1)) # Convert to binary

# Check INWA tag is correct.
